// <auto-generated />
namespace blog_yeni.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mert1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mert1));
        
        string IMigrationMetadata.Id
        {
            get { return "201511041517321_mert1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
